# Site settings
name: arsenalxj
email: arsenalxj@gmail.com
author: arsenalxj
url: 
resume_site: 
github: https://github.com/arslixiaojie/

#用来设置url，127.0.0.1:4000/xxx
baseurl: 
description: nothing
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: one gunner, always gunner
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: arslixiaojie

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

